// packages/generator/src/artifacts/qwik-jsx/jsx.ts
import type { Context } from '@bamboocss/core'
import { outdent } from 'outdent'

export function generateQwikJsxFactory(ctx: Context) {
  const { factoryName, componentName } = ctx.jsx

  return {
    js: outdent`
    import { h } from '@builder.io/qwik'
    ${ctx.file.import(
      'defaultShouldForwardProp, composeShouldForwardProps, composeCvaFn, getDisplayName',
      './factory-helper',
    )}
    ${ctx.file.import('isCssProperty', './is-valid-prop')}
    ${ctx.file.import('css, cx, cva', '../css/index')}
    ${ctx.file.import('splitProps, normalizeHTMLProps', '../helpers')}

    function styledFn(Dynamic, configOrCva = {}, options = {}) {
      const cvaFn = configOrCva.__cva__ || configOrCva.__recipe__ ? configOrCva : cva(configOrCva)

      const forwardFn = options.shouldForwardProp || defaultShouldForwardProp
      const shouldForwardProp = (prop) => {
        if (options.forwardProps?.includes(prop)) return true
        return forwardFn(prop, cvaFn.variantKeys)
      }

      const defaultProps = Object.assign(
        options.dataAttr && configOrCva.__name__ ? { 'data-recipe': configOrCva.__name__ } : {},
        options.defaultProps,
      )

      const __cvaFn__ = composeCvaFn(Dynamic.__cva__, cvaFn)
      const __shouldForwardProps__ = composeShouldForwardProps(Dynamic, shouldForwardProp)
      const __base__ = Dynamic.__base__ || Dynamic

      const ${componentName} = function ${componentName}(props) {
        const { as: Element = __base__, unstyled, children, className, ...restProps } = props

        const combinedProps = Object.assign({}, defaultProps, restProps)

        const [htmlProps, forwardedProps, variantProps, styleProps, elementProps] =
          splitProps(combinedProps, normalizeHTMLProps.keys, __shouldForwardProps__, __cvaFn__.variantKeys, isCssProperty)

        const { css: cssStyles, ...propStyles } = styleProps

        function recipeClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const compoundVariantStyles = __cvaFn__.__getCompoundVariantCss__?.(variantProps);
          return cx(__cvaFn__(variantProps, false), css(compoundVariantStyles, propStyles, cssStyles), combinedProps.class, className)
        }

        function cvaClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const cvaStyles = __cvaFn__.raw(variantProps)
          return cx(css(cvaStyles, propStyles, cssStyles), combinedProps.class, className)
        }

        const classes = () => {
          if (unstyled) {
            const { css: cssStyles, ...propStyles } = styleProps
            return cx(css(propStyles, cssStyles), combinedProps.class, className)
          }
          return configOrCva.__recipe__ ? recipeClass() : cvaClass()
        }

        return h(Element, {
          ...forwardedProps,
          ...elementProps,
          ...normalizeHTMLProps(htmlProps),
          class: classes(),
        }, children ?? combinedProps.children)
      }

      const name = getDisplayName(__base__)

      ${componentName}.displayName = \`${factoryName}.\${name}\`
      ${componentName}.__cva__ = __cvaFn__
      ${componentName}.__base__ = __base__
      ${componentName}.__shouldForwardProps__ = shouldForwardProp

      return ${componentName}
    }

    function createJsxFactory() {
      const cache = new Map()

      return new Proxy(styledFn, {
        apply(_, __, args) {
          return styledFn(...args)
        },
        get(_, el) {
          if (!cache.has(el)) {
            cache.set(el, styledFn(el))
          }
          return cache.get(el)
        },
      })
    }

    export const ${factoryName} = /* @__PURE__ */ createJsxFactory()

    `,
  }
}

// packages/generator/src/artifacts/solid-jsx/jsx.ts
import type { Context } from '@bamboocss/core'
import { outdent } from 'outdent'

export function generateSolidJsxFactory(ctx: Context) {
  const { componentName, factoryName } = ctx.jsx
  return {
    js: outdent`
    import { createMemo, mergeProps, splitProps } from 'solid-js'
    import { Dynamic, createComponent } from 'solid-js/web'
    ${ctx.file.import('css, cx, cva', '../css/index')}
    ${ctx.file.import('normalizeHTMLProps', '../helpers')}
    ${ctx.file.import(
      'composeCvaFn, composeShouldForwardProps, defaultShouldForwardProp, getDisplayName',
      './factory-helper',
    )}
    ${ctx.file.import('isCssProperty', './is-valid-prop')}

    function styledFn(element, configOrCva = {}, options = {}) {
      const cvaFn =
        configOrCva.__cva__ || configOrCva.__recipe__
          ? configOrCva
          : cva(configOrCva)

      const forwardFn = options.shouldForwardProp || defaultShouldForwardProp
      const shouldForwardProp = (prop) => {
        if (options.forwardProps?.includes(prop)) return true
        return forwardFn(prop, cvaFn.variantKeys)
      }

      const getDefaultProps = () => {
        const baseDefaults = options.dataAttr && configOrCva.__name__
          ? { 'data-recipe': configOrCva.__name__ }
          : {}
        const defaults = typeof options.defaultProps === 'function'
          ? options.defaultProps()
          : options.defaultProps
        return Object.assign(baseDefaults, defaults)
      }

      const __cvaFn__ = composeCvaFn(element.__cva__, cvaFn)
      const __shouldForwardProps__ = composeShouldForwardProps(
        element,
        shouldForwardProp
      )

      const ${componentName} = (props) => {
        const mergedProps = mergeProps(
          { as: element.__base__ || element },
          getDefaultProps(),
          props
        )

        const [localProps, restProps] = splitProps(mergedProps, [
          'as',
          'unstyled',
          'class',
          'className',
        ])

        const [htmlProps, aProps] = splitProps(restProps, normalizeHTMLProps.keys)

        const forwardedKeys = createMemo(() => {
          const keys = Object.keys(aProps)
          return keys.filter((prop) => __shouldForwardProps__(prop))
        })

        const [forwardedProps, variantProps, bProps] = splitProps(aProps, forwardedKeys(), __cvaFn__.variantKeys)

        const cssPropKeys = createMemo(() => {
          const keys = Object.keys(bProps)
          return keys.filter((prop) => isCssProperty(prop))
        })

        const [styleProps, elementProps] = splitProps(bProps, cssPropKeys())

        function recipeClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const compoundVariantStyles =
            __cvaFn__.__getCompoundVariantCss__?.(variantProps)
          return cx(
            __cvaFn__(variantProps, false),
            css(compoundVariantStyles, propStyles, cssStyles),
            localProps.class,
            localProps.className
          )
        }

        function cvaClass() {
          const { css: cssStyles, ...propStyles } = styleProps
          const cvaStyles = __cvaFn__.raw(variantProps)
          return cx(
            css(cvaStyles, propStyles, cssStyles),
            localProps.class,
            localProps.className
          )
        }

        const classes = () => {
          if (localProps.unstyled) {
            const { css: cssStyles, ...propStyles } = styleProps
            return cx(css(propStyles, cssStyles), localProps.class, localProps.className)
          }
          return configOrCva.__recipe__ ? recipeClass() : cvaClass()
        }

        if (forwardedProps.className) {
          delete forwardedProps.className
        }

        return createComponent(
          Dynamic,
          mergeProps(forwardedProps, elementProps, normalizeHTMLProps(htmlProps), {
            get component() {
              return localProps.as
            },
            get class() {
              return classes()
            },
          })
        )
      }

      const name = getDisplayName(element)

      ${componentName}.displayName = \`${factoryName}.\${name}\`
      ${componentName}.__cva__ = __cvaFn__
      ${componentName}.__base__ = element
      ${componentName}.__shouldForwardProps__ = shouldForwardProp

      return ${componentName}
    }

    function createJsxFactory() {
      const cache = new Map()

      return new Proxy(styledFn, {
        apply(_, __, args) {
          return styledFn(...args)
        },
        get(_, el) {
          if (!cache.has(el)) {
            cache.set(el, styledFn(el))
          }
          return cache.get(el)
        },
      })
    }

    export const ${factoryName} = /* @__PURE__ */ createJsxFactory()
    `,
  }
}
