// sandbox/qwik-ts/src/components/header.tsx
import { component$ } from '@builder.io/qwik'
import { QwikLogo } from './qwik-logo'
import { flex } from 'styled-system/patterns'
import { css } from 'styled-system/css'

export default component$(() => {
  return (
    <header>
      <div class={flex({ align: 'center', gap: '8px', justify: 'space-between' })}>
        <div class={css({ maxW: '20px' })}>
          <a href="/" title="qwik">
            <QwikLogo height={50} width={143} />
          </a>
        </div>
        <ul class={flex({ align: 'center', color: 'white', gap: '6' })}>
          <li>
            <a href="https://qwik.builder.io/docs/components/overview/" target="_blank">
              Docs
            </a>
          </li>
          <li>
            <a href="https://qwik.builder.io/examples/introduction/hello-world/" target="_blank">
              Examples
            </a>
          </li>
          <li>
            <a href="https://qwik.builder.io/tutorial/welcome/overview/" target="_blank">
              Tutorials
            </a>
          </li>
        </ul>
      </div>
    </header>
  )
})

// website/src/components/docs/header.tsx
import { Docs } from '.velite'
import { css } from '@/styled-system/css'
import { Flex } from '@/styled-system/jsx'
import { CopyMdxWidget } from './copy-mdx-widget'

interface Props {
  doc: Docs
}

export const Header = ({ doc }: Props) => {
  return (
    <Flex
      direction={{ base: 'column', md: 'row' }}
      justify={{ md: 'space-between' }}
      align="flex-start"
      gap="4"
      mb="12"
      mt="8"
    >
      <div>
        <h1
          className={css({
            fontSize: { base: '3xl', md: '4xl' },
            fontWeight: 'bold',
            lineHeight: 'tight',
            mb: 2
          })}
        >
          {doc.title}
        </h1>
        {doc.description && (
          <p className={css({ fontSize: 'lg', color: 'fg.muted', maxW: '3xl' })}>
            {doc.description}
          </p>
        )}
      </div>

      <CopyMdxWidget doc={doc} />
    </Flex>
  )
}
