// packages/generator/src/artifacts/qwik-jsx/pattern.ts
import type { Context } from '@bamboocss/core'
import type { ArtifactFilters } from '@bamboocss/types'
import { outdent } from 'outdent'
import { match } from 'ts-pattern'

export function generateQwikJsxPattern(ctx: Context, filters?: ArtifactFilters) {
  const { typeName, factoryName, styleProps: jsxStyleProps } = ctx.jsx

  const details = ctx.patterns.filterDetails(filters)

  return details.map((pattern) => {
    const { upperName, styleFnName, dashName, jsxName, props, blocklistType } = pattern
    const { description, jsxElement = 'div', deprecated } = pattern.config

    return {
      name: dashName,
      js: outdent`
      import { h } from '@builder.io/qwik'
      ${jsxStyleProps === 'minimal' ? ctx.file.import('mergeCss', '../css/css') : ''}
      ${ctx.file.import('splitProps', '../helpers')}
      ${ctx.file.import(styleFnName, `../patterns/${dashName}`)}
      ${ctx.file.import(factoryName, './factory')}

      export const ${jsxName} = /* @__PURE__ */ function ${jsxName}(props) {
        ${match(jsxStyleProps)
          .with(
            'none',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const mergedProps = { ref, ...restProps, css: styleProps }
          
          return h(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .with(
            'minimal',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const cssProps = { css: mergeCss(styleProps, props.css) }
          const mergedProps = { ...restProps, ...cssProps }

          return h(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .with(
            'all',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const mergedProps = { ...styleProps, ...restProps }
          
          return h(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .exhaustive()}
      }
      `,

      dts: outdent`
      import type { Component } from '@builder.io/qwik'
      ${ctx.file.importType(`${upperName}Properties`, `../patterns/${dashName}`)}
      ${ctx.file.importType(typeName, '../types/jsx')}
      ${ctx.file.importType('Assign, DistributiveOmit', '../types/system-types')}

      export interface ${upperName}Props extends Assign<${typeName}<'${jsxElement}'>, DistributiveOmit<${upperName}Properties, ${
        blocklistType || '""'
      }>> {}

      ${ctx.file.jsDocComment(description, { deprecated })}
      export declare const ${jsxName}: Component<${upperName}Props>
      `,
    }
  })
}

// packages/generator/src/artifacts/react-jsx/pattern.ts
import type { Context } from '@bamboocss/core'
import type { ArtifactFilters } from '@bamboocss/types'
import { outdent } from 'outdent'
import { match } from 'ts-pattern'

export function generateReactJsxPattern(ctx: Context, filters?: ArtifactFilters) {
  const { typeName, factoryName, styleProps: jsxStyleProps } = ctx.jsx

  const details = ctx.patterns.filterDetails(filters)

  return details.map((pattern) => {
    const { upperName, styleFnName, dashName, jsxName, props, blocklistType } = pattern
    const { description, jsxElement = 'div', deprecated } = pattern.config

    return {
      name: dashName,
      js: outdent`
      import { createElement, forwardRef } from 'react'
      ${jsxStyleProps === 'minimal' ? ctx.file.import('mergeCss', '../css/css') : ''}
      ${ctx.file.import('splitProps', '../helpers')}
      ${ctx.file.import(styleFnName, `../patterns/${dashName}`)}
      ${ctx.file.import(factoryName, './factory')}

      export const ${jsxName} = /* @__PURE__ */ forwardRef(function ${jsxName}(props, ref) {
        ${match(jsxStyleProps)
          .with(
            'none',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const mergedProps = { ref, ...restProps, css: styleProps }
          
          return createElement(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .with(
            'minimal',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const cssProps = { css: mergeCss(styleProps, props.css) }
          const mergedProps = { ref, ...restProps, ...cssProps }

          return createElement(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .with(
            'all',
            () => outdent`
          const [patternProps, restProps] = splitProps(props, ${JSON.stringify(props)})
          
          const styleProps = ${styleFnName}(patternProps)
          const mergedProps = { ref, ...styleProps, ...restProps }

          return createElement(${factoryName}.${jsxElement}, mergedProps)
          `,
          )
          .exhaustive()}
        })
      `,

      dts: outdent`
      import type { FunctionComponent } from 'react'
      ${ctx.file.importType(`${upperName}Properties`, `../patterns/${dashName}`)}
      ${ctx.file.importType(typeName, '../types/jsx')}
      ${ctx.file.importType('DistributiveOmit', '../types/system-types')}

      export interface ${upperName}Props extends ${upperName}Properties, DistributiveOmit<${typeName}<'${jsxElement}'>, keyof ${upperName}Properties ${blocklistType}> {}

      ${ctx.file.jsDocComment(description, { deprecated })}
      export declare const ${jsxName}: FunctionComponent<${upperName}Props>
      `,
    }
  })
}
